apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-scheduler
  name: custom-scheduler
spec:
  selector:
    matchLabels:
      app: custom-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-scheduler
      name: custom-scheduler
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: prometheus-test
          image: prom/prometheus
        - name: prometheus-adapter-test
          image: directxman12/k8s-prometheus-adapter:latest
        - name: kubectl
          image: bitnami/kubectl:latest
          args:
            - "proxy"
        - name: custom-scheduler
          image: divyaprem/kubernetes-custom-scheduler:5.0.0
